import {
  BarChart3,
  Calendar,
  Calculator,
  Check,
  Clock3,
  Copy,
  CreditCard,
  Dice5,
  Eye,
  EyeOff,
  ExternalLink,
  FileText,
  LayoutDashboard,
  Lightbulb,
  Link as LinkIcon,
  Lock,
  Pin,
  QrCode,
  RefreshCw,
  Rocket,
  Search,
  Tag,
  TrendingUp,
  Type,
  Wrench,
} from 'lucide-react'

export const iconMap = {
  calculate: Calculator,
  rocket_launch: Rocket,
  link: LinkIcon,
  lock: Lock,
  calendar_month: Calendar,
  schedule: Clock3,
  qr_code: QrCode,
  trending_up: TrendingUp,
  payments: CreditCard,
  text_fields: Type,
  label: Tag,
  casino: Dice5,
  lightbulb: Lightbulb,
  show_chart: BarChart3,
  dashboard: LayoutDashboard,
  article: FileText,
  check: Check,
  content_copy: Copy,
  construction: Wrench,
  push_pin: Pin,
  search: Search,
  visibility: Eye,
  visibility_off: EyeOff,
  refresh: RefreshCw,
  open_in_new: ExternalLink,
}
