const AUDIT_UI_COPY = {
  en: {
    badgeWorker: 'Remote audit',
    badgeFallback: 'Limited check',
    coverage: 'Coverage',
    checkedChecks: 'Verified',
    categoryScores: 'Category overview',
    scoreBreakdown: 'Scoring breakdown',
    topPriorities: 'Priority fixes',
    allGoodTitle: 'No active issues found',
    allGoodText: 'All verified checks passed. The breakdown below shows the full score picture.',
    filtersTitle: 'Show checks',
    filterIssues: 'Issues',
    filterAll: 'All',
    filterErrors: 'Errors',
    filterWarnings: 'Warnings',
    filterPassed: 'Passed',
    filterUnavailable: 'Not checked',
    whyItMatters: 'Why it matters',
    recommendation: 'How to improve',
    benchmark: 'Target',
    currentValue: 'Current',
    rawSignals: 'Raw audit data',
    rawHint: 'Technical snapshot returned by the audit source.',
    noRecommendation: 'No action needed.',
    notChecked: 'Signal unavailable in the current audit mode.',
    impact: 'Score impact',
    scoreOutOf: (earned, max) => `${earned}/${max}`,
    checksCount: (checked, total) => `${checked}/${total}`,
    scoreSummary: (score) => score >= 90
      ? 'Strong on-page signals across all verified checks.'
      : score >= 70
        ? 'Most signals look good. A few targeted improvements available.'
        : 'Several signals need work before the page looks fully optimized.',
    status: {
      pass: 'Pass',
      warning: 'Warn',
      fail: 'Error',
      na: 'N/A',
    },
    categories: {
      technical: 'Technical',
      metadata: 'Metadata',
      content: 'Content',
      enhancements: 'Enhancements',
      accessibility: 'Media',
    },
    labels: {
      httpStatus: 'HTTP status',
      htmlContent: 'HTML response',
      httpsUrl: 'HTTPS final URL',
      robots: 'Robots directives',
      titlePresence: 'Title tag',
      titleLength: 'Title length',
      descriptionPresence: 'Meta description',
      descriptionLength: 'Description length',
      canonical: 'Canonical URL',
      h1Presence: 'Primary H1',
      h1Length: 'H1 length',
      h2Coverage: 'H2 headings',
      openGraph: 'Open Graph',
      twitter: 'Twitter cards',
      structuredData: 'Structured data',
      altCoverage: 'Image alt',
      linkMix: 'Link signals',
    },
    why: {
      httpStatus: 'Search engines need the page to resolve successfully before any other signal matters.',
      htmlContent: 'The audit should target a regular HTML page, not a file or API response.',
      httpsUrl: 'HTTPS is a basic trust and indexing expectation for public pages.',
      robots: 'Robots directives can block indexing even when everything else is correct.',
      titlePresence: 'The title tag is one of the strongest on-page signals and shapes the search snippet.',
      titleLength: 'A well-sized title is easier to read and less likely to be truncated in search results.',
      descriptionPresence: 'Meta descriptions influence snippet quality and click-through context.',
      descriptionLength: 'A balanced description is easier to display cleanly in search results.',
      canonical: 'Canonical tags help search engines understand which version of a page should rank.',
      h1Presence: 'A clear H1 helps align the page topic with search intent and document structure.',
      h1Length: 'An H1 should be specific enough to clarify the topic without becoming bloated.',
      h2Coverage: 'Subheadings help structure the content for both users and search engines.',
      openGraph: 'Open Graph tags improve link previews in messengers and social platforms.',
      twitter: 'Twitter/X cards add consistent preview data beyond default link scraping.',
      structuredData: 'Structured data can improve eligibility for enhanced search presentation.',
      altCoverage: 'Descriptive alt text improves accessibility and helps search engines understand images.',
      linkMix: 'A healthy link profile indicates crawl paths and page context.',
    },
    fallbackNoticeBody: 'The remote audit endpoint is temporarily unavailable. This is a limited browser-based check — some signals could not be evaluated. Try again in a moment.',
    workerIcon: 'worker',
  },
  ru: {
    badgeWorker: 'Удалённый аудит',
    badgeFallback: 'Ограниченная проверка',
    coverage: 'Покрытие',
    checkedChecks: 'Проверено',
    categoryScores: 'Обзор по категориям',
    scoreBreakdown: 'Детализация оценки',
    topPriorities: 'Приоритетные исправления',
    allGoodTitle: 'Все проверенные сигналы в порядке',
    allGoodText: 'Активных проблем не найдено. Ниже — полная картина оценки.',
    filtersTitle: 'Показать проверки',
    filterIssues: 'Проблемы',
    filterAll: 'Все',
    filterErrors: 'Ошибки',
    filterWarnings: 'Предупреждения',
    filterPassed: 'ОК',
    filterUnavailable: 'Не проверено',
    whyItMatters: 'Почему это важно',
    recommendation: 'Что улучшить',
    benchmark: 'Ориентир',
    currentValue: 'Текущее',
    rawSignals: 'Сырые данные аудита',
    rawHint: 'Технический снимок, возвращённый источником аудита.',
    noRecommendation: 'Доработка не требуется.',
    notChecked: 'Этот сигнал недоступен в текущем режиме аудита.',
    impact: 'Влияние на оценку',
    scoreOutOf: (earned, max) => `${earned}/${max}`,
    checksCount: (checked, total) => `${checked}/${total}`,
    scoreSummary: (score) => score >= 90
      ? 'Сильные on-page сигналы по всем проверенным проверкам.'
      : score >= 70
        ? 'Основные сигналы в порядке. Доступны точечные улучшения.'
        : 'Есть несколько проблем, которые заметно тянут оценку вниз.',
    status: {
      pass: 'ОК',
      warning: 'Вним.',
      fail: 'Ошибка',
      na: 'Н/Д',
    },
    categories: {
      technical: 'Техническое',
      metadata: 'Метаданные',
      content: 'Контент',
      enhancements: 'Расширения',
      accessibility: 'Медиа',
    },
    labels: {
      httpStatus: 'HTTP-статус',
      htmlContent: 'HTML-страница',
      httpsUrl: 'Итоговый URL (HTTPS)',
      robots: 'Robots-директивы',
      titlePresence: 'Тег title',
      titleLength: 'Длина title',
      descriptionPresence: 'Meta description',
      descriptionLength: 'Длина description',
      canonical: 'Canonical URL',
      h1Presence: 'Основной H1',
      h1Length: 'Длина H1',
      h2Coverage: 'Подзаголовки H2',
      openGraph: 'Open Graph',
      twitter: 'Twitter cards',
      structuredData: 'Структурированные данные',
      altCoverage: 'Alt у изображений',
      linkMix: 'Ссылочные сигналы',
    },
    why: {
      httpStatus: 'Пока страница не отдает корректный ответ, остальные SEO-сигналы не имеют смысла.',
      htmlContent: 'Для индексации важна именно обычная HTML-страница, а не файл или API-ответ.',
      httpsUrl: 'HTTPS — базовый сигнал доверия и нормальная практика для индексируемых страниц.',
      robots: 'Robots может заблокировать индексацию даже при хороших остальных сигналах.',
      titlePresence: 'Title — один из главных on-page сигналов и основа поискового сниппета.',
      titleLength: 'Сбалансированный title читается лучше и реже обрезается в выдаче.',
      descriptionPresence: 'Meta description помогает контролировать смысл и привлекательность сниппета.',
      descriptionLength: 'Слишком короткое или длинное описание хуже работает в сниппете.',
      canonical: 'Canonical помогает поисковикам понять, какая версия страницы является основной.',
      h1Presence: 'Понятный H1 помогает связать тему страницы с поисковым интентом и структурой документа.',
      h1Length: 'H1 должен быть достаточно конкретным, но не перегруженным.',
      h2Coverage: 'Подзаголовки помогают структурировать контент и улучшают сканируемость страницы.',
      openGraph: 'Open Graph отвечает за качественный превью-блок в соцсетях и мессенджерах.',
      twitter: 'Twitter/X cards дополняют социальные превью и повышают консистентность ссылок.',
      structuredData: 'Структурированные данные повышают шанс на расширенное отображение в поиске.',
      altCoverage: 'Описательные alt улучшают доступность и помогают поисковикам понимать изображения.',
      linkMix: 'Ссылки помогают понять структуру страницы и её связь с другими документами.',
    },
    fallbackNoticeBody: 'Удалённый эндпоинт SEO-аудита временно недоступен. Это ограниченная браузерная проверка — часть сигналов не могла быть оценена. Попробуйте ещё раз через некоторое время.',
    workerIcon: 'worker',
  },
}

const AUDIT_CATEGORY_ORDER = [
  { id: 'technical' },
  { id: 'metadata' },
  { id: 'content' },
  { id: 'enhancements' },
  { id: 'accessibility' },
]

export { AUDIT_UI_COPY, AUDIT_CATEGORY_ORDER }
